name: Pull Request - Check Protobuf - Go

on:
  pull_request: 
    paths: 
      - 'proto/**.proto'
  workflow_dispatch:

jobs:
  generate-protobuf-go:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          ref: "${{ github.head_ref }}"
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'
          check-latest: false
          cache: true
      - name: Generate Go Source
        shell: bash
        run: |
          make pipeline-build
